site_name: RST Documentation
repo_url: https://github.com/superdarn/rst
theme: readthedocs
extra_css: [css/rst.css]
markdown_extensions:
    - extra
    - admonition
    - toc

nav:
    - Home: index.md
    - About: about.md
    - Installation:
            - Linux: user_guide/linux_install.md
            - MacOSX: user_guide/mac_install.md
    - RST HOWTO: 
        - Data Processing: 
                - RAWACF to FITACF: user_guide/make_fit.md
                - FITACF to GRID: user_guide/make_grid.md
                - GRID to MAP: user_guide/map_grid.md
        - Plotting Data: 
                - Range-time Plots: user_guide/time_plot.md
                - Field of View Plots: user_guide/fov_plot.md
                - Field Plots: user_guide/field_plot.md
                - Grid Plots: user_guide/grid_plot.md
                - Convection Plots: user_guide/map_plot.md
                - Customized Colors: user_guide/colors.md
    - SuperDARN: 
        - Introduction: superdarn/introduction.md
        - Radars: superdarn/radar_table.md 
        - Acknowledging SuperDARN Data: superdarn/acknowledgments.md
        - Data Formats:
                - File Naming: superdarn/formats/file_naming.md
    
